"""modified

Revision ID: 64f29bcf0622
Revises: b413cd0952ac
Create Date: 2024-11-22 23:14:01.776164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f29bcf0622'
down_revision: Union[str, None] = 'b413cd0952ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_updates_offset_fkey', 'chat_updates', type_='foreignkey')
    op.create_foreign_key(None, 'chat_updates', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_updates', type_='foreignkey')
    op.create_foreign_key('chat_updates_offset_fkey', 'chat_updates', 'chats', ['offset'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
